### ISSUE TITLE
Uncaught ReferenceError: settings is not defined

### ISSUE THREAD

**Issue by steverandy** [kim-company/videojs-chromecast#12]
```javascript
function ChromecastComponent(player, settings1) {
  this.settings = settings1;
  ChromecastComponent.__super__.constructor.call(this, player, settings);
  if (!player.controls()) {
    this.disable();
  }
  this.hide();
  this.initializeApi();
}
```

Shouldn't `settings` be `this.settings`?

**Comment by philipgiuliani** [comment]
This seems to be a bug of the new coffeescript compiler. Havent tested that
before releasing the new version sorry. I will fix this today!

Steve Randy Tantra <notifications@github.com> schrieb am Mi., 15. Apr. 2015
04:28:

**Comment by philipgiuliani** [comment]
This one is fixed, i hope there is no other error. I currently have not time to test it. Before I release a new version, could you try it out?

I updated: https://github.com/kim-company/videojs-chromecast/tree/master/dist

**Comment by steverandy** [comment]
It's fixed. Thanks!

**Comment by philipgiuliani** [comment]
Thanks for reporting it! I should test the builds next time.. :)
