### ISSUE TITLE
VideoJS 5 Issue

### ISSUE THREAD

**Issue by DHoogland** [kim-company/videojs-chromecast#17]
Hey,

Could you/we maybe update this to VideoJS 5?
It would be awesome!

**Comment by philipgiuliani** [comment]
Hi! Yes i definetly want to update it for VideoJS 5, but i think i will rewrite it in ES6. Currently i dont have enough time. But i will need it for my own project soon, than i update it! If somebody would like to help, would be great! I planned a rewrite to also address some older issues.

**Comment by KaySackey** [comment]
I'm curious. I'm just starting out using Video JS, so ofcourse I went with 5.0 but I've found that a lot of plugins are non compatible. Dev-to-dev, do you have any idea of what changed under the hood? Is this kind of something that'll need a full-rewrite of every plugin out there?

**Comment by philipgiuliani** [comment]
Hi @9cloud! Yes they have updated quite a lot... They rewrote VideoJS to the all new ES6 and are running babeljs.io as a transpiler to JS for current browsers.

Here you can see the changes.
https://github.com/videojs/video.js/wiki/5.0-Change-Details

I can ensure that in the next month(s) i will update this here. I'll also rewrite it to ES6.

**Comment by begriffs** [comment]
+1 on video.js 5 support

**Comment by joshmn** [comment]
+1

**Comment by razerrazer** [comment]
+1

**Comment by Jrubensson** [comment]
+1

**Comment by Bechrissed** [comment]
+1

**Comment by AvremelM** [comment]
There's a [fork ](https://github.com/PeterMHoward/videojs-chromecast) of this that works on 5.0.

**Comment by DHoogland** [comment]
Thanks @HodofHod

**Comment by Jrubensson** [comment]
@HodofHod It doesn't work with desktop, or am I just doing something wrong?

**Comment by razerrazer** [comment]
How is it going with this?

**Comment by ntamblyn** [comment]
Any updates on this ?

**Comment by onigetoc** [comment]
+1

**Comment by askaliuk** [comment]
This fork works:
https://github.com/PeterMHoward/videojs-chromecast

Tested on videojs 5.8.2

**Comment by DHoogland** [comment]
@askaliuk I can't seem to get the button to work/show up. The console is fine.
Here a screenshot: http://i.imgur.com/7Gk3q6O.png

Using:
 "video.js": "^5.8.2",
 "videojs-chromecast": "PeterMHoward/videojs-chromecast#master"

**Comment by askaliuk** [comment]
@DHoogland I would recommend to debug it.
The code is simple to understand. Make sure that Chromecast device in available from Chrome and works from YouTube.

You may even do it without repeating their build process.
Just download and add [main script](https://github.com/PeterMHoward/videojs-chromecast/blob/master/dist/videojs.chromecast.js) to the page. Put some `console.log` in ChromecastComponent. In your case I would start with cast session initialization (`ChromecastComponent.prototype.onSessionSuccess`)

**Comment by DHoogland** [comment]
@askaliuk thanks for your reply. When I remove the appId it works. Any idea why?

The only thing i'm missing right now is Subtitles & closed captions in the cast plugin ^^ Maybe when I got some spare time!

**Comment by ntamblyn** [comment]
Have you registered your chromecast device within the google developer console? 

Assuming you have set up a test receiver app. 

If so i had this problem and by physicaly turning it off and on again it worked.

**Comment by DHoogland** [comment]
@ntamblyn I think I had to publish it first before I could try it. It seems to work now, awesome! thanks everyone for the time!
